function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 11-Nov-2021 21:14:49

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop = 7100;     % Stopband Frequency
    % Fpass = 8000;     % Passband Frequency
    % Astop = 20;       % Stopband Attenuation (dB)
    % Apass = 10.4576;  % Passband Ripple (dB)
    % Fs    = 44100;    % Sampling Frequency
    %
    % h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'stopband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -2 1 1 -0.496743186156479 0.685732537500094; 1 -2 1 ...
        1 -0.384969197985725 0.30641973773431; 1 -2 1 1 -0.328410931547332 ...
        0.114485328452316; 1 -2 1 1 -0.304222067216249 0.0323987356525554], ...
        'ScaleValues', [0.545618930914143; 0.422847233930009; ...
        0.360724064999912; 0.334155200717201; 1]);
end

s = double(x);
y = step(Hd,s);

